/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreDesenvolvimentoRouteImport } from './routes/sobre-desenvolvimento'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as RankingInfoRouteImport } from './routes/ranking-info'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as SobreDesenvolvimentoChangelogAdminRouteImport } from './routes/sobre-desenvolvimento.changelog-admin'
import { Route as SobreDesenvolvimentoAdminRouteImport } from './routes/sobre-desenvolvimento.admin'
import { Route as RankingCompareRouteImport } from './routes/ranking_.compare'
import { Route as PlayersUserIdRouteImport } from './routes/players.$userId'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as HooksPresenceWindowOpenedRouteImport } from './routes/hooks.presence-window-opened'
import { Route as HooksAdminUndoRouteImport } from './routes/hooks.admin-undo'
import { Route as HooksAdminPendingReminderRouteImport } from './routes/hooks.admin-pending-reminder'
import { Route as HooksAdminActionRouteImport } from './routes/hooks.admin-action'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups.$groupId.index'
import { Route as GroupsGroupIdSeasonsRouteImport } from './routes/groups.$groupId.seasons'
import { Route as GroupsGroupIdDuelRouteImport } from './routes/groups.$groupId.duel'
import { Route as ApiPushVapidPublicKeyRouteImport } from './routes/api.push.vapid-public-key'
import { Route as GroupsGroupIdSeasonsIndexRouteImport } from './routes/groups.$groupId.seasons.index'
import { Route as GroupsGroupIdSeasonsSeasonIdRouteImport } from './routes/groups.$groupId.seasons.$seasonId'
import { Route as ApiOgPlayerUserIdRouteImport } from './routes/api.og.player.$userId'
import { Route as ApiOgGroupGroupIdRouteImport } from './routes/api.og.group.$groupId'
import { Route as GroupsGroupIdSeasonsSeasonIdIndexRouteImport } from './routes/groups.$groupId.seasons.$seasonId.index'
import { Route as GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRouteImport } from './routes/groups.$groupId.seasons.$seasonId.rounds.$roundId'

const SobreDesenvolvimentoRoute = SobreDesenvolvimentoRouteImport.update({
  id: '/sobre-desenvolvimento',
  path: '/sobre-desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingInfoRoute = RankingInfoRouteImport.update({
  id: '/ranking-info',
  path: '/ranking-info',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const SobreDesenvolvimentoChangelogAdminRoute =
  SobreDesenvolvimentoChangelogAdminRouteImport.update({
    id: '/changelog-admin',
    path: '/changelog-admin',
    getParentRoute: () => SobreDesenvolvimentoRoute,
  } as any)
const SobreDesenvolvimentoAdminRoute =
  SobreDesenvolvimentoAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => SobreDesenvolvimentoRoute,
  } as any)
const RankingCompareRoute = RankingCompareRouteImport.update({
  id: '/ranking_/compare',
  path: '/ranking/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUserIdRoute = PlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksPresenceWindowOpenedRoute =
  HooksPresenceWindowOpenedRouteImport.update({
    id: '/hooks/presence-window-opened',
    path: '/hooks/presence-window-opened',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAdminUndoRoute = HooksAdminUndoRouteImport.update({
  id: '/hooks/admin-undo',
  path: '/hooks/admin-undo',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAdminPendingReminderRoute =
  HooksAdminPendingReminderRouteImport.update({
    id: '/hooks/admin-pending-reminder',
    path: '/hooks/admin-pending-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAdminActionRoute = HooksAdminActionRouteImport.update({
  id: '/hooks/admin-action',
  path: '/hooks/admin-action',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdSeasonsRoute = GroupsGroupIdSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdDuelRoute = GroupsGroupIdDuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const ApiPushVapidPublicKeyRoute = ApiPushVapidPublicKeyRouteImport.update({
  id: '/api/push/vapid-public-key',
  path: '/api/push/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSeasonsIndexRoute =
  GroupsGroupIdSeasonsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GroupsGroupIdSeasonsRoute,
  } as any)
const GroupsGroupIdSeasonsSeasonIdRoute =
  GroupsGroupIdSeasonsSeasonIdRouteImport.update({
    id: '/$seasonId',
    path: '/$seasonId',
    getParentRoute: () => GroupsGroupIdSeasonsRoute,
  } as any)
const ApiOgPlayerUserIdRoute = ApiOgPlayerUserIdRouteImport.update({
  id: '/api/og/player/$userId',
  path: '/api/og/player/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgGroupGroupIdRoute = ApiOgGroupGroupIdRouteImport.update({
  id: '/api/og/group/$groupId',
  path: '/api/og/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSeasonsSeasonIdIndexRoute =
  GroupsGroupIdSeasonsSeasonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GroupsGroupIdSeasonsSeasonIdRoute,
  } as any)
const GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute =
  GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRouteImport.update({
    id: '/rounds/$roundId',
    path: '/rounds/$roundId',
    getParentRoute: () => GroupsGroupIdSeasonsSeasonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/comparar': typeof CompararRoute
  '/dev': typeof DevRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-info': typeof RankingInfoRoute
  '/seasons': typeof SeasonsRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-desenvolvimento': typeof SobreDesenvolvimentoRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/hooks/admin-action': typeof HooksAdminActionRoute
  '/hooks/admin-pending-reminder': typeof HooksAdminPendingReminderRoute
  '/hooks/admin-undo': typeof HooksAdminUndoRoute
  '/hooks/presence-window-opened': typeof HooksPresenceWindowOpenedRoute
  '/invite/$code': typeof InviteCodeRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/ranking/compare': typeof RankingCompareRoute
  '/sobre-desenvolvimento/admin': typeof SobreDesenvolvimentoAdminRoute
  '/sobre-desenvolvimento/changelog-admin': typeof SobreDesenvolvimentoChangelogAdminRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/groups/$groupId/duel': typeof GroupsGroupIdDuelRoute
  '/groups/$groupId/seasons': typeof GroupsGroupIdSeasonsRouteWithChildren
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/api/og/group/$groupId': typeof ApiOgGroupGroupIdRoute
  '/api/og/player/$userId': typeof ApiOgPlayerUserIdRoute
  '/groups/$groupId/seasons/$seasonId': typeof GroupsGroupIdSeasonsSeasonIdRouteWithChildren
  '/groups/$groupId/seasons/': typeof GroupsGroupIdSeasonsIndexRoute
  '/groups/$groupId/seasons/$seasonId/': typeof GroupsGroupIdSeasonsSeasonIdIndexRoute
  '/groups/$groupId/seasons/$seasonId/rounds/$roundId': typeof GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/comparar': typeof CompararRoute
  '/dev': typeof DevRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-info': typeof RankingInfoRoute
  '/seasons': typeof SeasonsRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-desenvolvimento': typeof SobreDesenvolvimentoRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/hooks/admin-action': typeof HooksAdminActionRoute
  '/hooks/admin-pending-reminder': typeof HooksAdminPendingReminderRoute
  '/hooks/admin-undo': typeof HooksAdminUndoRoute
  '/hooks/presence-window-opened': typeof HooksPresenceWindowOpenedRoute
  '/invite/$code': typeof InviteCodeRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/ranking/compare': typeof RankingCompareRoute
  '/sobre-desenvolvimento/admin': typeof SobreDesenvolvimentoAdminRoute
  '/sobre-desenvolvimento/changelog-admin': typeof SobreDesenvolvimentoChangelogAdminRoute
  '/groups': typeof GroupsIndexRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/groups/$groupId/duel': typeof GroupsGroupIdDuelRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/api/og/group/$groupId': typeof ApiOgGroupGroupIdRoute
  '/api/og/player/$userId': typeof ApiOgPlayerUserIdRoute
  '/groups/$groupId/seasons': typeof GroupsGroupIdSeasonsIndexRoute
  '/groups/$groupId/seasons/$seasonId': typeof GroupsGroupIdSeasonsSeasonIdIndexRoute
  '/groups/$groupId/seasons/$seasonId/rounds/$roundId': typeof GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/comparar': typeof CompararRoute
  '/dev': typeof DevRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/ranking-info': typeof RankingInfoRoute
  '/seasons': typeof SeasonsRoute
  '/sistema': typeof SistemaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-desenvolvimento': typeof SobreDesenvolvimentoRouteWithChildren
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/hooks/admin-action': typeof HooksAdminActionRoute
  '/hooks/admin-pending-reminder': typeof HooksAdminPendingReminderRoute
  '/hooks/admin-undo': typeof HooksAdminUndoRoute
  '/hooks/presence-window-opened': typeof HooksPresenceWindowOpenedRoute
  '/invite/$code': typeof InviteCodeRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/ranking_/compare': typeof RankingCompareRoute
  '/sobre-desenvolvimento/admin': typeof SobreDesenvolvimentoAdminRoute
  '/sobre-desenvolvimento/changelog-admin': typeof SobreDesenvolvimentoChangelogAdminRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/groups/$groupId/duel': typeof GroupsGroupIdDuelRoute
  '/groups/$groupId/seasons': typeof GroupsGroupIdSeasonsRouteWithChildren
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/api/og/group/$groupId': typeof ApiOgGroupGroupIdRoute
  '/api/og/player/$userId': typeof ApiOgPlayerUserIdRoute
  '/groups/$groupId/seasons/$seasonId': typeof GroupsGroupIdSeasonsSeasonIdRouteWithChildren
  '/groups/$groupId/seasons/': typeof GroupsGroupIdSeasonsIndexRoute
  '/groups/$groupId/seasons/$seasonId/': typeof GroupsGroupIdSeasonsSeasonIdIndexRoute
  '/groups/$groupId/seasons/$seasonId/rounds/$roundId': typeof GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/comparar'
    | '/dev'
    | '/groups'
    | '/history'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/ranking-info'
    | '/seasons'
    | '/sistema'
    | '/sitemap.xml'
    | '/sobre-desenvolvimento'
    | '/admin/inbox'
    | '/admin/metrics'
    | '/groups/$groupId'
    | '/hooks/admin-action'
    | '/hooks/admin-pending-reminder'
    | '/hooks/admin-undo'
    | '/hooks/presence-window-opened'
    | '/invite/$code'
    | '/players/$userId'
    | '/ranking/compare'
    | '/sobre-desenvolvimento/admin'
    | '/sobre-desenvolvimento/changelog-admin'
    | '/groups/'
    | '/api/push/vapid-public-key'
    | '/groups/$groupId/duel'
    | '/groups/$groupId/seasons'
    | '/groups/$groupId/'
    | '/api/og/group/$groupId'
    | '/api/og/player/$userId'
    | '/groups/$groupId/seasons/$seasonId'
    | '/groups/$groupId/seasons/'
    | '/groups/$groupId/seasons/$seasonId/'
    | '/groups/$groupId/seasons/$seasonId/rounds/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/comparar'
    | '/dev'
    | '/history'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/ranking-info'
    | '/seasons'
    | '/sistema'
    | '/sitemap.xml'
    | '/sobre-desenvolvimento'
    | '/admin/inbox'
    | '/admin/metrics'
    | '/hooks/admin-action'
    | '/hooks/admin-pending-reminder'
    | '/hooks/admin-undo'
    | '/hooks/presence-window-opened'
    | '/invite/$code'
    | '/players/$userId'
    | '/ranking/compare'
    | '/sobre-desenvolvimento/admin'
    | '/sobre-desenvolvimento/changelog-admin'
    | '/groups'
    | '/api/push/vapid-public-key'
    | '/groups/$groupId/duel'
    | '/groups/$groupId'
    | '/api/og/group/$groupId'
    | '/api/og/player/$userId'
    | '/groups/$groupId/seasons'
    | '/groups/$groupId/seasons/$seasonId'
    | '/groups/$groupId/seasons/$seasonId/rounds/$roundId'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/comparar'
    | '/dev'
    | '/groups'
    | '/history'
    | '/landing'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/ranking'
    | '/ranking-info'
    | '/seasons'
    | '/sistema'
    | '/sitemap.xml'
    | '/sobre-desenvolvimento'
    | '/admin/inbox'
    | '/admin/metrics'
    | '/groups/$groupId'
    | '/hooks/admin-action'
    | '/hooks/admin-pending-reminder'
    | '/hooks/admin-undo'
    | '/hooks/presence-window-opened'
    | '/invite/$code'
    | '/players/$userId'
    | '/ranking_/compare'
    | '/sobre-desenvolvimento/admin'
    | '/sobre-desenvolvimento/changelog-admin'
    | '/groups/'
    | '/api/push/vapid-public-key'
    | '/groups/$groupId/duel'
    | '/groups/$groupId/seasons'
    | '/groups/$groupId/'
    | '/api/og/group/$groupId'
    | '/api/og/player/$userId'
    | '/groups/$groupId/seasons/$seasonId'
    | '/groups/$groupId/seasons/'
    | '/groups/$groupId/seasons/$seasonId/'
    | '/groups/$groupId/seasons/$seasonId/rounds/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  CompararRoute: typeof CompararRoute
  DevRoute: typeof DevRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  RankingInfoRoute: typeof RankingInfoRoute
  SeasonsRoute: typeof SeasonsRoute
  SistemaRoute: typeof SistemaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreDesenvolvimentoRoute: typeof SobreDesenvolvimentoRouteWithChildren
  AdminInboxRoute: typeof AdminInboxRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  HooksAdminActionRoute: typeof HooksAdminActionRoute
  HooksAdminPendingReminderRoute: typeof HooksAdminPendingReminderRoute
  HooksAdminUndoRoute: typeof HooksAdminUndoRoute
  HooksPresenceWindowOpenedRoute: typeof HooksPresenceWindowOpenedRoute
  InviteCodeRoute: typeof InviteCodeRoute
  PlayersUserIdRoute: typeof PlayersUserIdRoute
  RankingCompareRoute: typeof RankingCompareRoute
  ApiPushVapidPublicKeyRoute: typeof ApiPushVapidPublicKeyRoute
  ApiOgGroupGroupIdRoute: typeof ApiOgGroupGroupIdRoute
  ApiOgPlayerUserIdRoute: typeof ApiOgPlayerUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-desenvolvimento': {
      id: '/sobre-desenvolvimento'
      path: '/sobre-desenvolvimento'
      fullPath: '/sobre-desenvolvimento'
      preLoaderRoute: typeof SobreDesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-info': {
      id: '/ranking-info'
      path: '/ranking-info'
      fullPath: '/ranking-info'
      preLoaderRoute: typeof RankingInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/sobre-desenvolvimento/changelog-admin': {
      id: '/sobre-desenvolvimento/changelog-admin'
      path: '/changelog-admin'
      fullPath: '/sobre-desenvolvimento/changelog-admin'
      preLoaderRoute: typeof SobreDesenvolvimentoChangelogAdminRouteImport
      parentRoute: typeof SobreDesenvolvimentoRoute
    }
    '/sobre-desenvolvimento/admin': {
      id: '/sobre-desenvolvimento/admin'
      path: '/admin'
      fullPath: '/sobre-desenvolvimento/admin'
      preLoaderRoute: typeof SobreDesenvolvimentoAdminRouteImport
      parentRoute: typeof SobreDesenvolvimentoRoute
    }
    '/ranking_/compare': {
      id: '/ranking_/compare'
      path: '/ranking/compare'
      fullPath: '/ranking/compare'
      preLoaderRoute: typeof RankingCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$userId': {
      id: '/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof PlayersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/presence-window-opened': {
      id: '/hooks/presence-window-opened'
      path: '/hooks/presence-window-opened'
      fullPath: '/hooks/presence-window-opened'
      preLoaderRoute: typeof HooksPresenceWindowOpenedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/admin-undo': {
      id: '/hooks/admin-undo'
      path: '/hooks/admin-undo'
      fullPath: '/hooks/admin-undo'
      preLoaderRoute: typeof HooksAdminUndoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/admin-pending-reminder': {
      id: '/hooks/admin-pending-reminder'
      path: '/hooks/admin-pending-reminder'
      fullPath: '/hooks/admin-pending-reminder'
      preLoaderRoute: typeof HooksAdminPendingReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/admin-action': {
      id: '/hooks/admin-action'
      path: '/hooks/admin-action'
      fullPath: '/hooks/admin-action'
      preLoaderRoute: typeof HooksAdminActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/seasons': {
      id: '/groups/$groupId/seasons'
      path: '/seasons'
      fullPath: '/groups/$groupId/seasons'
      preLoaderRoute: typeof GroupsGroupIdSeasonsRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/duel': {
      id: '/groups/$groupId/duel'
      path: '/duel'
      fullPath: '/groups/$groupId/duel'
      preLoaderRoute: typeof GroupsGroupIdDuelRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/api/push/vapid-public-key': {
      id: '/api/push/vapid-public-key'
      path: '/api/push/vapid-public-key'
      fullPath: '/api/push/vapid-public-key'
      preLoaderRoute: typeof ApiPushVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/seasons/': {
      id: '/groups/$groupId/seasons/'
      path: '/'
      fullPath: '/groups/$groupId/seasons/'
      preLoaderRoute: typeof GroupsGroupIdSeasonsIndexRouteImport
      parentRoute: typeof GroupsGroupIdSeasonsRoute
    }
    '/groups/$groupId/seasons/$seasonId': {
      id: '/groups/$groupId/seasons/$seasonId'
      path: '/$seasonId'
      fullPath: '/groups/$groupId/seasons/$seasonId'
      preLoaderRoute: typeof GroupsGroupIdSeasonsSeasonIdRouteImport
      parentRoute: typeof GroupsGroupIdSeasonsRoute
    }
    '/api/og/player/$userId': {
      id: '/api/og/player/$userId'
      path: '/api/og/player/$userId'
      fullPath: '/api/og/player/$userId'
      preLoaderRoute: typeof ApiOgPlayerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/group/$groupId': {
      id: '/api/og/group/$groupId'
      path: '/api/og/group/$groupId'
      fullPath: '/api/og/group/$groupId'
      preLoaderRoute: typeof ApiOgGroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/seasons/$seasonId/': {
      id: '/groups/$groupId/seasons/$seasonId/'
      path: '/'
      fullPath: '/groups/$groupId/seasons/$seasonId/'
      preLoaderRoute: typeof GroupsGroupIdSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdSeasonsSeasonIdRoute
    }
    '/groups/$groupId/seasons/$seasonId/rounds/$roundId': {
      id: '/groups/$groupId/seasons/$seasonId/rounds/$roundId'
      path: '/rounds/$roundId'
      fullPath: '/groups/$groupId/seasons/$seasonId/rounds/$roundId'
      preLoaderRoute: typeof GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRouteImport
      parentRoute: typeof GroupsGroupIdSeasonsSeasonIdRoute
    }
  }
}

interface GroupsGroupIdSeasonsSeasonIdRouteChildren {
  GroupsGroupIdSeasonsSeasonIdIndexRoute: typeof GroupsGroupIdSeasonsSeasonIdIndexRoute
  GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute: typeof GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute
}

const GroupsGroupIdSeasonsSeasonIdRouteChildren: GroupsGroupIdSeasonsSeasonIdRouteChildren =
  {
    GroupsGroupIdSeasonsSeasonIdIndexRoute:
      GroupsGroupIdSeasonsSeasonIdIndexRoute,
    GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute:
      GroupsGroupIdSeasonsSeasonIdRoundsRoundIdRoute,
  }

const GroupsGroupIdSeasonsSeasonIdRouteWithChildren =
  GroupsGroupIdSeasonsSeasonIdRoute._addFileChildren(
    GroupsGroupIdSeasonsSeasonIdRouteChildren,
  )

interface GroupsGroupIdSeasonsRouteChildren {
  GroupsGroupIdSeasonsSeasonIdRoute: typeof GroupsGroupIdSeasonsSeasonIdRouteWithChildren
  GroupsGroupIdSeasonsIndexRoute: typeof GroupsGroupIdSeasonsIndexRoute
}

const GroupsGroupIdSeasonsRouteChildren: GroupsGroupIdSeasonsRouteChildren = {
  GroupsGroupIdSeasonsSeasonIdRoute:
    GroupsGroupIdSeasonsSeasonIdRouteWithChildren,
  GroupsGroupIdSeasonsIndexRoute: GroupsGroupIdSeasonsIndexRoute,
}

const GroupsGroupIdSeasonsRouteWithChildren =
  GroupsGroupIdSeasonsRoute._addFileChildren(GroupsGroupIdSeasonsRouteChildren)

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdDuelRoute: typeof GroupsGroupIdDuelRoute
  GroupsGroupIdSeasonsRoute: typeof GroupsGroupIdSeasonsRouteWithChildren
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdDuelRoute: GroupsGroupIdDuelRoute,
  GroupsGroupIdSeasonsRoute: GroupsGroupIdSeasonsRouteWithChildren,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface SobreDesenvolvimentoRouteChildren {
  SobreDesenvolvimentoAdminRoute: typeof SobreDesenvolvimentoAdminRoute
  SobreDesenvolvimentoChangelogAdminRoute: typeof SobreDesenvolvimentoChangelogAdminRoute
}

const SobreDesenvolvimentoRouteChildren: SobreDesenvolvimentoRouteChildren = {
  SobreDesenvolvimentoAdminRoute: SobreDesenvolvimentoAdminRoute,
  SobreDesenvolvimentoChangelogAdminRoute:
    SobreDesenvolvimentoChangelogAdminRoute,
}

const SobreDesenvolvimentoRouteWithChildren =
  SobreDesenvolvimentoRoute._addFileChildren(SobreDesenvolvimentoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  CompararRoute: CompararRoute,
  DevRoute: DevRoute,
  GroupsRoute: GroupsRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  RankingInfoRoute: RankingInfoRoute,
  SeasonsRoute: SeasonsRoute,
  SistemaRoute: SistemaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreDesenvolvimentoRoute: SobreDesenvolvimentoRouteWithChildren,
  AdminInboxRoute: AdminInboxRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  HooksAdminActionRoute: HooksAdminActionRoute,
  HooksAdminPendingReminderRoute: HooksAdminPendingReminderRoute,
  HooksAdminUndoRoute: HooksAdminUndoRoute,
  HooksPresenceWindowOpenedRoute: HooksPresenceWindowOpenedRoute,
  InviteCodeRoute: InviteCodeRoute,
  PlayersUserIdRoute: PlayersUserIdRoute,
  RankingCompareRoute: RankingCompareRoute,
  ApiPushVapidPublicKeyRoute: ApiPushVapidPublicKeyRoute,
  ApiOgGroupGroupIdRoute: ApiOgGroupGroupIdRoute,
  ApiOgPlayerUserIdRoute: ApiOgPlayerUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
