UPDATE public.release_notes SET version = CASE title
WHEN 'Atalho do painel de desenvolvimento' THEN 'v0.36.0'
WHEN 'Cancelar rodadas pela agenda' THEN 'v0.37.0'
WHEN 'Acesso ao cancelamento na Home' THEN 'v0.37.1'
WHEN 'Ordem manual dos jogos sorteados' THEN 'v0.38.0'
WHEN 'Super tie-break em duelos' THEN 'v0.38.1'
WHEN 'Partidas não jogadas' THEN 'v0.39.0'
WHEN 'Sets interrompidos no ranking' THEN 'v0.40.0'
WHEN 'Rodadas abertas sem sair da tela' THEN 'v0.40.1'
WHEN 'Todos os resultados em uma ação' THEN 'v0.40.2'
WHEN 'Resumo de Elo após a rodada' THEN 'v0.40.3'
WHEN 'Estender uma temporada' THEN 'v0.40.4'
WHEN 'Engrenagem discreta do administrador' THEN 'v0.41.0'
WHEN 'Elegibilidade do ranking por sets' THEN 'v0.41.1'
WHEN 'Retorno sem recarregar a página' THEN 'v0.41.2'
WHEN 'Jogadores inativos no ranking' THEN 'v0.41.3'
WHEN 'Resultado enviado aos participantes' THEN 'v0.41.4'
WHEN 'Última rodada antes da próxima' THEN 'v0.41.5'
WHEN 'Compartilhar resumo da rodada' THEN 'v0.42.0'
WHEN 'Compartilhar ranking' THEN 'v0.42.1'
WHEN 'Ranking recalculado após editar placar' THEN 'v0.42.2'
WHEN 'Últimas cinco partidas em ordem' THEN 'v0.42.3'
WHEN 'Ranking sem painel duplicado no computador' THEN 'v0.42.4'
WHEN 'Um aviso por rodada de resultados' THEN 'v0.42.5'
WHEN 'Edição de nomes dos membros' THEN 'v0.43.0'
WHEN 'Evolução de Elo do último grupo' THEN 'v0.43.1'
WHEN 'Proteção de dados e imagens' THEN 'v0.43.2'
ELSE version END
WHERE title IN ('Atalho do painel de desenvolvimento','Cancelar rodadas pela agenda','Acesso ao cancelamento na Home','Ordem manual dos jogos sorteados','Super tie-break em duelos','Partidas não jogadas','Sets interrompidos no ranking','Rodadas abertas sem sair da tela','Todos os resultados em uma ação','Resumo de Elo após a rodada','Estender uma temporada','Engrenagem discreta do administrador','Elegibilidade do ranking por sets','Retorno sem recarregar a página','Jogadores inativos no ranking','Resultado enviado aos participantes','Última rodada antes da próxima','Compartilhar resumo da rodada','Compartilhar ranking','Ranking recalculado após editar placar','Últimas cinco partidas em ordem','Ranking sem painel duplicado no computador','Um aviso por rodada de resultados','Edição de nomes dos membros','Evolução de Elo do último grupo','Proteção de dados e imagens') AND released_at >= '2026-05-07 14:40:00+00' AND released_at <= '2026-09-30 13:24:00+00';